"""Build flat source-backed tables and an artifact-tool payload; no Excel authoring."""
from pathlib import Path
import pandas as pd,numpy as np,json,ast
W=Path(__file__).resolve().parent;A=W/'analysis';O=W/'tables';O.mkdir(exist_ok=True)
def read(name):return pd.read_csv(A/name)
def clean(df):return {'columns':df.columns.tolist(),'data':df.astype(object).where(pd.notna(df),None).values.tolist()}
tables=[]
def table(num,title,sections,legend,source):
 ss=[]
 for label,df in sections:
  df.to_csv(O/f'Table_S{num}_{label}.csv',index=False)
  z=clean(df);ss.append({'label':label,'columns':z['columns'],'data':z['data']})
 d={'number':num,'sheet':f'S{num:02d}','title':title,'legend':legend,'source':source,'sections':ss};tables.append(d)
 (O/f'Table_S{num}_legend.md').write_text(f'**Supplementary Table S{num}. {title}.** {legend}\n',encoding='utf8')
geo='https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc='
mapping=pd.read_csv(W/'source_review/GSE243013_sample_clinical_map.csv')
table(1,'Single-cell patient mapping and eligibility',[('patient_map',mapping)],'One row per deposited patient/sample identifier. Original GEO and publisher clinical fields are retained with explicit eligibility, missingness and disagreements. Primary eligibility requires source matching, documented anti-PD-1 therapy and concordant known pathological response; 224 records qualify. RFS fields use publisher Table S5. No identifiers were merged by inferred prefixes.',geo+'GSE243013')
tree=ast.parse((W/'remote_sources/gse243013_fullcell_module_scoring.py').read_text());sig=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='SIGNATURES' for t in n.targets))
genes=pd.DataFrame([{'module':k,'n_genes':len(v),'gene_symbols':';'.join(v),'single_cell_formula':'Mean across cells of ln(1 + 10000 * summed module UMI / total cellular UMI)','bulk_formula':'Within-cohort standardized mean of gene-wise z scores of normalized log expression','interpretation':'Transcriptional proxy; no direct functional measurement'} for k,v in sig.items()])
table(2,'Complete gene-program definitions',[('gene_programs',genes),('singlecell_coverage',pd.read_csv(W/'inputs/Supplementary_Table_91_GSE243013_fullcell_signature_gene_coverage.csv')),('spatial_coverage',read('spatial_coverage.csv'))],'The 12 original programs and full gene lists are retained. Gene sharing between modules is visible in the lists. Spatial scoring requires at least two genes and 50% module coverage. Module labels describe the genes selected rather than directly measured functional states.',geo+'GSE243013; '+geo+'GSE221733')
table(3,'Patient-level transcriptional contrasts',[('all_contrasts',read('sc_all_contrasts.csv')),('stage_source',read('sc_stage_source_sensitivity.csv')),('centre_adjustment',read('sc_center_sensitivity.csv'))],'All estimable major-lineage, resolved-lineage and subtype response contrasts, including prespecified cohort and cell-count sensitivities. Effect estimates are non-MPR minus MPR/pCR on the stated score scale. HC3 confidence intervals and Benjamini–Hochberg q values use the complete testing family per analysis/model. Unknown stage remains missing; model-specific n and response counts are complete-case counts.',geo+'GSE243013')
table(4,'Immune-subset abundance contrasts',[('abundance',read('sc_abundance_contrasts.csv'))],'Subset fractions use all recovered cells within the corresponding broad lineage, including explicit zero counts for absent subtypes. Estimates and intervals are adjusted percentage-point differences. The testing family contains every evaluable subset, not only selected significant populations.',geo+'GSE243013')
table(5,'Composition and technical adjustment of T/NK transcription',[('composition_models',read('sc_composition_models.csv')),('centre_sensitivity',read('sc_composition_center_sensitivity.csv'))],'Clinical models adjust for age, sex, histology, stage and documented chemotherapy status. Composition models add Treg, NK and terminal-CD8 fractions; depth models add log mean library size; the final sensitivity adds original collection centre. All use 217 complete-case patients. Conditional coefficients are not mediation effects.',geo+'GSE243013')
table(6,'Within-patient CD8 and NK contrasts',[('paired_lineage',read('sc_CD8_NK_interaction.csv'))],'Each outcome is the CD8 score minus the NK score from the same patient, with at least 100 cells per lineage. The non-MPR coefficient tests whether this paired difference changes with response. All 12 programs constitute the correction family.',geo+'GSE243013')
sc=read('sc_composite_scores.csv');keep=['sampleID','pathological_response','nonMPR','score']+[c for c in sc if c.startswith('z_')]
table(7,'Discovery score components and discrimination',[('patient_scores',sc[keep]),('scaling',read('sc_score_scaling.csv')),('AUC',read('sc_auc_benchmarks.csv')),('PDL1_AUC',read('sc_pdl1_benchmarks.csv')),('RFS_Cindex',read('sc_rfs_cindex.csv'))],'The complete six-component score requires T/NK and myeloid coverage and is available in 212 patients. AUCs compare non-MPR versus MPR/pCR; all component comparisons use that common set. PD-L1 comparisons use 101 common patients. RFS C-index comparisons use 154 patients and 30 events. Intervals use 2,000 patient bootstrap replicates, stratified for AUCs. Scaling parameters and equal component weights are supplied.',geo+'GSE243013')
table(8,'Clinical follow-up and recurrence models',[('clinical_records',read('sc_clinical_followup.csv')),('Cox_models',read('sc_rfs_models.csv')),('PDL1_logistic',read('sc_pdl1_adjusted_models.csv')),('PH_diagnostics',read('sc_rfs_ph_assumption.csv'))],'Original clinical records preserve numeric versus categorical PD-L1 information. RFS time is months and 1 denotes an event. Cox models use Efron ties; HRs refer to one SD of score or non-MPR versus response. Different available-data denominators are explicit. score_equation_max_abs measures the largest absolute fitted Cox score-equation component. Schoenfeld tests use the Kaplan–Meier time transformation.',geo+'GSE243013')
bulkmeta=pd.concat([pd.read_csv(W/'source_review'/f) for f in ['GSE126044_verified_analysis_metadata.csv','GSE135222_verified_analysis_metadata.csv','GSE93157_NSCLC35_verified_analysis_metadata.csv']],ignore_index=True)
table(9,'External bulk-cohort source metadata',[('clinical_records',bulkmeta)],'One row per NSCLC specimen. GSE126044 response is original durable-benefit classification, with ORR also independently coded. GSE135222 PFS coding and clinical benefit match original supplementary records. GSE93157 ORR and DCR derive from best response, preserving the discordant generic GEO response field. Unverified survival fields are retained as raw source values and are not analysed as known events.',geo+'GSE126044; '+geo+'GSE135222; '+geo+'GSE93157')
table(10,'Bulk assay coverage and score scaling',[('gene_coverage',read('bulk_gene_coverage.csv')),('score_scaling',read('bulk_score_scaling.csv'))],'All requested, measured and missing genes are listed. Program eligibility requires at least two variable measured genes and 50% coverage. Six-module proxies require all six components; the four-immune-module proxy is explicitly separate. Scaling occurs within each cohort without outcome-fitted weights. GSE93157 uses the author-normalized processed log2 matrix.',geo+'GSE126044; '+geo+'GSE135222; '+geo+'GSE93157')
b=read('bulk_scores.csv');cols=['cohort','expression_id','patient_id','six_module_proxy','four_immune_module_proxy','No durable benefit','No objective response','Progressive disease','pfs_time_days','pfs_event']+list(sig)+['negative_CD274','negative_CYTOTOXICITY']
table(11,'External expression-score outcome analyses',[('patient_scores',b[[x for x in cols if x in b]]),('AUC',read('bulk_auc_models.csv')),('Cox_models',read('bulk_survival_models.csv')),('Cindex',read('bulk_cindex_models.csv'))],'The higher-score/nonresponse orientation remains fixed. All eligible-specimen and fresh-tissue analyses and every evaluable feature are reported. AUC intervals use 2,000 stratified patient bootstraps; exact rank separation can make the empirical interval degenerate, in which case the interval is explicitly non-estimable rather than [0,0]. PFS Cox and C-index models use GSE135222 only. q values are calculated within the reported cohort/endpoint/analysis family.',geo+'GSE126044; '+geo+'GSE135222; '+geo+'GSE93157')
table(12,'Spatial patient and region mapping',[('AOI_metadata',pd.read_csv(W/'source_review/GSE221733_AOI_clinical_map.csv')),('technical_covariates',pd.read_csv(W/'source_review/GSE221733_initial_probe_technical_covariates.csv'))],'All 93 deposited areas are preserved, with membership in normalized and QC matrices. The normalized matrix contains 68 areas/40 patients; 67 areas/39 patients have known response. Complete pairs comprise 23 ROIs from 21 patients. Negative-probe background is calculated from 75 original negative probes. Patient labels are normalized only for whitespace.',geo+'GSE221733')
table(13,'All paired spatial gene-compartment contrasts',[('gene_contrasts',read('spatial_gene_compartments.csv'))],'Paired PanCK-positive minus PanCK-negative differences are first calculated within original ROI, then averaged equally within patient; 21 independent patients enter each gene test. Deposited and within-area median-centred relative scales are reported. t-based 95% intervals and BH correction cover all 1,812 genes per scale.',geo+'GSE221733')
table(14,'Nested spatial program models',[('mixed_models',read('spatial_mixed_models.csv')),('background_sensitivity',read('spatial_background_sensitivity.csv'))],'Models contain fixed compartment, response and interaction terms plus patient and ROI-within-patient random intercepts. panck is the compartment effect among nonresponders; responder is the response effect in PanCK-negative regions. Nuclei and negative-probe adjustment are identified. Variance components, convergence, AOI/patient/ROI counts and per-term BH q values are retained, including near-zero variance components.',geo+'GSE221733')
table(15,'All spatial gene-response comparisons',[('gene_response',read('spatial_gene_response.csv'))],'Response comparisons use patient-averaged expression within each PanCK compartment, with Welch confidence intervals and complete 1,812-gene BH families per compartment/scale. No gene is omitted because its response association is nonsignificant.',geo+'GSE221733')
table(16,'NHANES selection and descriptive measures',[('selection',read('nhanes_selection.csv')),('quartiles',read('nhanes_quartiles.csv')),('missingness',read('nhanes_missingness.csv'))],'The selection series reports interviewed participants, age eligibility, positive fasting weights, complete components/smoking and complete covariates. Quartiles use survey-weighted cut points; medians are weighted, while n and lung-cancer case counts are unweighted. Missingness denominators refer to age-eligible participants with positive fasting weight. CRP is mg/L; WBC is 10^9/L; BMI is kg/m^2; TyG and NLR are dimensionless.', 'https://wwwn.cdc.gov/nchs/nhanes/')
table(17,'Survey-weighted metabolic-inflammatory associations',[('models',read('nhanes_models.csv'))],'Each exposure is standardized to one survey-weighted SD. MIDS_no_crp, MIDS_no_wbc and MIDS_no_nlr omit their named inflammatory outcome; metabolic_only uses TyG and BMI only. Models use fasting weights WTSAF2YR/2 and masked strata/PSUs, with the listed covariates and restrictions. Continuous estimates are coefficients for log(1 + outcome). Lung-cancer counts are descriptive; sparse, separated models are not reported as finite odds-ratio estimates.', 'https://wwwn.cdc.gov/nchs/nhanes/')
table(18,'Genetic instruments and locus annotations',[('instruments',read('mr_instrument_locus_annotations.csv'))],'All 13 instrument–exposure records (12 distinct variants) are retained, including reused variants across traits. F statistics use squared beta/SE. Original locus labels are preserved alongside actual GRCh37 gene coordinates and distance outside the gene interval. Proximity to a named gene does not make the instrument a verified molecular perturbation.', 'https://gwas.mrcieu.ac.uk/; https://grch37.ensembl.org/')
table(19,'Harmonized genetic associations',[('harmonized_variants',read('mr_harmonised.csv'))],'All 9,398 harmonized variant records supporting the reconstructed screen, including exposure/outcome effect alleles, association estimates, standard errors, harmonization indicators and trait identifiers. Original records are provided to permit independent reconstruction of Wald and inverse-variance estimates.', 'https://gwas.mrcieu.ac.uk/')
table(20,'Complete exploratory immune-trait genetic screen',[('all_tests',read('mr_complete_results.csv'))],'All 7,224 tested associations and the single full-family BH correction. Effects retain the original continuous-trait scale and are not converted to drug-effect odds ratios. Two-SNP Q statistics are reported where applicable. Egger and MR-PRESSO are unavailable with one or two variants; colocalization was not performed. Approximate variance-explained comparisons are descriptive direction checks rather than validated molecular directionality tests.', 'https://gwas.mrcieu.ac.uk/; https://doi.org/10.1038/s41588-020-0684-4; https://doi.org/10.1038/s41588-020-00718-6')
(O/'supplementary_tables_payload.json').write_text(json.dumps(tables,ensure_ascii=False,allow_nan=False),encoding='utf8')
# Editable main-text tables.
cohorts=pd.DataFrame([
 ['GSE243013','Post-neoadjuvant immune-cell RNA sequencing','224 patients; 1,173,843 cells','Pathological response; RFS subset','Discovery of immune states'],
 ['GSE221733','Pretreatment spatial RNA profiling','40 patients; 68 normalized areas','39 patients with response; 21 paired patients','Tumour–stromal localization'],
 ['GSE126044','Pretreatment bulk RNA sequencing','16 patients; 11 fresh and 5 FFPE','Durable benefit; objective response','External gene-set proxy'],
 ['GSE135222','Bulk tumour RNA sequencing','27 patients; 21 progression events','Durable benefit; PFS','External gene-set proxy'],
 ['GSE93157','Archival/pretreatment NanoString','35 NSCLC patients','Objective response; disease control','Partial-panel immune proxy'],
 ['NHANES 2015–2018','Population questionnaire and laboratory tests','3,045 complete-component adults','Continuous inflammatory measurements','Host metabolic context'],
 ['Metabolic-trait GWAS','Inherited metabolic-trait instruments','13 instrument–exposure records; 7,224 tests','731 immune traits','Exploratory genetic associations']
],columns=['Dataset','Specimen and assay','Available sample','Endpoint','Analytical role'])
cl=pd.read_csv(W/'source_review/GSE243013_primary224_analysis_metadata.csv');rows=[]
for label,func in [('Patients',lambda z:str(len(z))),('Age, median (IQR), years',lambda z:f'{z.age.median():.0f} ({z.age.quantile(.25):.0f}–{z.age.quantile(.75):.0f})'),('Male',lambda z:str(z.gender.eq('M').sum())),('Squamous histology',lambda z:str(z.histology.eq('LUSC').sum())),('Stage I–II',lambda z:str(z.stage_S1.fillna('').str.match('^I{1,2}[^I]').sum())),('Stage III',lambda z:str(z.stage_S1.fillna('').str.startswith('III').sum())),('Stage unavailable',lambda z:str(z.stage_S1.isna().sum())),('Chemotherapy documented',lambda z:str(z.regimen_class.eq('documented_anti_PD1_with_chemotherapy').sum())),('PD-L1 category available',lambda z:str(z.PDL1_TPS_category.ne('unavailable').sum())),('Recurrence follow-up available',lambda z:str(z.RFS_status.notna().sum())),('Recurrence events',lambda z:str(z.RFS_status.fillna(0).sum().astype(int)))]:
 rows.append([label]+[func(cl[cl.pathological_response.eq(g)]) for g in ['non-MPR','MPR','pCR']])
t2=pd.DataFrame(rows,columns=['Characteristic','Non-MPR (n=103)','MPR (n=40)','pCR (n=81)'])
main=[{'number':1,'title':'Cohort designs and analytical roles','columns':cohorts.columns.tolist(),'data':cohorts.values.tolist(),'legend':'Datasets are analysed independently and inform different biological questions. RFS, recurrence-free survival; PFS, progression-free survival; FFPE, formalin-fixed paraffin-embedded; GWAS, genome-wide association study. Sample counts refer to the available design and may differ from complete-case model denominators.'},{'number':2,'title':'Characteristics of the primary single-cell cohort','columns':t2.columns.tolist(),'data':t2.values.tolist(),'legend':'Values are unweighted patient counts unless indicated otherwise. Source clinical Table S1 is used for stage and chemotherapy documentation. Unknown stage remains missing, and 21 patients with unavailable chemotherapy details are not classified as monotherapy. PD-L1 categories include seven values reported only as <1%. MPR, major pathological response; pCR, pathological complete response; IQR, interquartile range.'}]
(O/'main_tables.json').write_text(json.dumps(main,ensure_ascii=False),encoding='utf8')
for x in main:(O/f'Table_{x["number"]}_legend.md').write_text(f'**Table {x["number"]}. {x["title"]}.** {x["legend"]}\n',encoding='utf8')
print('Supplementary tables:',len(tables),'sections:',sum(len(t['sections']) for t in tables));print(t2.to_string(index=False))
